output_dir: results/test
with_drone: True
max_time: 200
fps: 2

distance_rescale: 1

initial_positions:
  RED:
    ARTILLERY: [[50,400],[50,400]]
    DRONE: [[650,350],[650,350]]
    TANK: [[400,350],[400,350]]
    ANTI_TANK: [[350,250],[350,250]]
    INFANTRY: [
      [350,250],[370,250]
    ]
    COMMAND_POST: [[350,300]]
  BLUE:
    ARTILLERY: [[100,350],[100,350]]
    DRONE: [[100,300],[100,300]]
    TANK: [[650,100],[665,100]]
    ANTI_TANK: [[500,105],[505,105]]
    INFANTRY: [
      [495,95],[490,95]
    ]
    COMMAND_POST: [[630,200]]

num_artillery_red: 2
num_artillery_blue: 2
num_drone_red: 2
num_drone_blue: 2
num_tank_red: 2
num_tank_blue: 2
num_at_red: 2
num_at_blue: 2
num_infantry_red: 2
num_infantry_blue: 2
num_cp_red: 1
num_cp_blue: 1